### ISSUE TITLE
Course Issues

### ISSUE THREAD

**Issue by tylermcginnis** [uidotdev/advanced-javascript-course#1]
### Example comment

Section title: JavaScript Inheritance and the ProtoType Chain
issue: Typo in this sentence, "The Animal clss is the perfect base class."

**Comment by Sgouws** [comment]
Section title: The JavaScript Event Loop: A Simple Guide
issue: The 'Post' is duplicated and appears twice - in its entirety - on the page. With the first post having some escaped HTML tags showing (\<br />)

**Comment by UncleJazzmus** [comment]
Section title: JavaScript Inheritance and the ProtoType Chain
issue: Shouldn't the sleep and play methods in the ES6 Animal class have length parameters?
