### ISSUE TITLE
Exposed <br /> tags in event loop post

### ISSUE THREAD

**Issue by bigethan** [uidotdev/advanced-javascript-course#3]
Section Title: The JavaScript Event Loop: A Simple Guide

issue:  The image that shows Wadworth's concurrent process has visible BR tags around it. It's the image after the paragraph beginning "With his new strategy, Wadsworth is able to prioritize picking up the kids on time..."

<img width="327" alt="Screen Shot 2019-07-27 at 2 36 20 PM" src="https://user-images.githubusercontent.com/627/61995130-ef135b80-b07b-11e9-909b-5153ff59977e.png">

**Comment by tylermcginnis** [comment]
Fixed. Thanks!
