### ISSUE TITLE
baked not caked?

### ISSUE THREAD

**Issue by bigethan** [uidotdev/advanced-javascript-course#4]
Section:JavaScript Inheritance and the Prototype Chain

Issue: Typo, where `caked` is used rather than `baked` in the string `What’s interesting about JavaScript is the same patterns you’ve learned these last few posts are directly caked into the language itself.`  (not sure if it's a language thing, but I've never seen caked used that way)

**Comment by tylermcginnis** [comment]
Fixed. Thanks!
